### PR TITLE
Tell current player

### LINKED ISSUE #5: There should be a players turn marker in the list
If we have multiple players, I think there should be a way of telling whos turn it is at the moment.
This helps to keep the game going, if someone doesn't pay attention.
Happens all the time in a tabletop setting as well.

### PR DESCRIPTION
**Pull request by Al2Klimov**
fixes #5

@theFeu Is it sufficient?

### CODE REVIEW

**Comment by theFeu** [comment]
I think it is actually a lot more interesting who plays the next card - maybe we can just highlight the first:child of the table with CSS to make it more obvious that that is the current player?

**Comment by Al2Klimov** [comment]
The _current player_ at :first-child is always being awaited-for which card they'll play _on top_ of the _last one_. But as the _current player_, facing e.g a +2, you wanna scream at the one _who just played it_, don’t you?

**Comment by theFeu** [comment]
Nono, you want to scream at the person who is supposed to be playing the card *at the moment*, because they are not paying attention ;)

**Comment by Al2Klimov** [comment]
Better?

**Comment by theFeu** [comment]
Very nice!
Me likey!

**Pull request merged**
